### PR TITLE
links homework

### PR DESCRIPTION
**Pull request by gummer11**
Add
-one absolute link
-2 relative links other pages and back
-1 relative link inside the page

### CODE REVIEW

**Comment by virag-ky** [comment]
You are almost done! I advise you to have only 1 `h1` element per page so the rest can be anything from between h2-h6.
Here is a link (the section is highlighted in purple): https://www.boia.org/blog/3-common-subheading-mistakes-that-can-create-accessibility-issues#:~:text=You%20should%20also%20try%20to,to%20justify%20two%20separate%20headings.

**Comment by gummer11** [comment]
Thank you for your helping, I have sent a new version, i used one h1 but more h2 elements on one page, I hope it is fine now, if not just let me know i will change it again. Thank you!

**Comment by virag-ky** [comment]
Yes, it's great now. It is just a good practice to have only one `h1` element per page. 😃

**Comment by gummer11** [comment]
Oh, happy hours then! 😊 Thank you Virag, that you teaching us, and for your patience! I think i have done all my homework (last week i was on holiday, so i missed to do it in time). I am looking forward your next lession and homework! 😁 Best wishes! Gummer

**Pull request merged**
