### PR TITLE
Proctor branch

### PR DESCRIPTION
**Pull request by V180465**
Hi Virag:

This is Michael.  I started doing your HTML Youtube assignments  this is the first on creating a pull request.  We created the HTML boilerplate  and created the branch.  I apologize I did this exercise, I failed to do the commits like you instructed.  But I am glad I stuck with it.

Michael :)

### CODE REVIEW

**Comment by V180465** [comment]
Hi Virag, after completing the assignment I forgot to add the sub-folder to encapulsate the index.html file.  I went back in and created the folder in the local repository and then pushed it back to the remote with the new branch also.  I did not want to submit inadequate work.  Thank you.  Michael.

**Comment by virag-ky** [comment]
Hi Michael!

You are almost done, except you deleted the other student's homework and the Readme file for this folder.
I suggest that you try out `git revert <commit_hash>` to go back to where you started. The commit hash has to be the hash of the first commit (since you made 5 commits already). I assume this might be that commit hash: f0f931bb44ac9e0f44adf1c54a2ef30dfaa6b9d1. So try `git revert f0f931bb44ac9e0f44adf1c54a2ef30dfaa6b9d1`. And make sure that in the Gummer folder, he has his index.html file there and also the Readme file for this repo with the homework instructions. 😃

**Comment by V180465** [comment]
Hi Virag:

Sorry for deleting the file :( I hope it did not interfere with the assignment of anyone.  After I finish class will go back and do the "git revert" command.

Thank you.

Michael

**Comment by V180465** [comment]
I am a disaster with this

**Comment by virag-ky** [comment]
Alright Michael, no worries, this is how we all learn 😄

**Comment by V180465** [comment]
Mulțumesc Virag, ești o comoară de profesor. :)

**Pull request closed without merging**
